apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "68mi"
        cpu: "100m" #1/10th of the CPU
      limits:   #limits should be equal or greater than requests
        memory: "80mi"
        cpu: "250m"