apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: roboshop
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port



# 3.231.145.51 | 172.31.13.202 | t3.micro | https://github.com/tsword24/k8s-resources.git
# [ ec2-user@ip-172-31-13-202 ~/k8s-resources ]$ kubectl apply -f 13-service.yaml
# service/nginx created

# 3.231.145.51 | 172.31.13.202 | t3.micro | https://github.com/tsword24/k8s-resources.git
# [ ec2-user@ip-172-31-13-202 ~/k8s-resources ]$ kubectl get svc
# NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
# kubernetes   ClusterIP   10.100.0.1       <none>        443/TCP   45m
# nginx        ClusterIP   10.100.166.200   <none>        80/TCP    13s

# 3.231.145.51 | 172.31.13.202 | t3.micro | https://github.com/tsword24/k8s-resources.git
# [ ec2-user@ip-172-31-13-202 ~/k8s-resources ]$ kubectl describe service nginx
# Name:                     nginx
# Namespace:                default
# Labels:                   <none>
# Annotations:              <none>
# Selector:                 component=frontend,environment=dev,project=roboshop
# Type:                     ClusterIP
# IP Family Policy:         SingleStack
# IP Families:              IPv4
# IP:                       10.100.166.200
# IPs:                      10.100.166.200
# Port:                     <unset>  80/TCP
# TargetPort:               80/TCP
# Endpoints:                                    ==> when a pod is created with the labels and it gets registered with the service it shows up as endpoint here 
# Session Affinity:         None
# Internal Traffic Policy:  Cluster
# Events:                   <none>