apiVersion: v1
kind: Service
metadata:
  name: np-nginx
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environment: dev
    service: np-service
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port