apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    environment: dev
    service: lb-service
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port
    nodePort: 30000